version: 2.1

orbs:
  wp-svn: studiopress/wp-svn@0.2

jobs:
  test:
    docker:
      - image: cimg/php:8.1-node
    working_directory: ~/project
    steps:
      - checkout
      - prepare-environment
      - run: composer phpcs

  zip_artifacts:
    docker:
      - image: cimg/php:8.1-node
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Node dependencies
          command: |
            npm ci
      - run:
          name: Install wp-cli
          command: |
            mkdir -p /tmp/wp-cli
            curl -o /tmp/wp-cli/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            chmod +x /tmp/wp-cli/wp
            echo 'export PATH=/tmp/wp-cli:$PATH' >> $BASH_ENV
            source $BASH_ENV
            wp --info
      - run:
          name: Build plugin zips and WPE info.json
          command: |
            npm run zip:all
      - store_artifacts:
          path: artifacts/wp.org
          destination: wp.org
      - store_artifacts:
          path: artifacts/wpe
          destination: wpe

  svn_deploy_dry_run:
    docker:
      - image: cimg/php:8.1-node
    working_directory: ~/project
    steps:
      - checkout
      - wp-svn/deploy-plugin:
          dry-run: true
          plugin-path: .

  svn_deploy_tag:
    docker:
      - image: cimg/php:8.1-node
    working_directory: ~/project
    steps:
      - checkout
      - wp-svn/deploy-plugin:
          plugin-path: .

commands:
  prepare-environment:
    description: "Install dependencies."
    steps:
      - run: composer install

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - zip_artifacts:
          requires:
            - test
      - approval-for-plugin-deploy:
          type: approval
          requires:
            - svn_deploy_dry_run
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - approval-for-deploy-tested-up-to-bump:
          type: approval
          requires:
            - test
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /^bump-tested-up-to.*/
      - wp-svn/deploy-tested-up-to-bump:
          context: genesis-svn
          requires:
            - approval-for-deploy-tested-up-to-bump
      - svn_deploy_dry_run:
          requires:
            - test
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - wp-svn/check-versions:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              only: /^release\/.*/
      - svn_deploy_tag:
          context: genesis-svn
          requires:
            - wp-svn/check-versions
            - svn_deploy_dry_run
            - approval-for-plugin-deploy
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
